# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation_vl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humor_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('tweet_id', models.BigIntegerField()),
                ('tweet_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='annotation_vl',
            name='tweet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Tweet'),
        ),
    ]
