# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='hashtags',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='reply_to_user',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='reply_to_user_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweet_to_user',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweet_to_user_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_followers',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
