# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_auto_20160408_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation_vl',
            name='content_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='annotation_vl',
            name='distance',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='annotation_vl',
            name='fear',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='annotation_vl',
            name='humor_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='annotation_vl',
            name='source',
            field=models.CharField(max_length=20),
        ),
    ]
