# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_auto_20160408_1020'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annotation_vl',
            unique_together=set([('tweet_id', 'student_id')]),
        ),
    ]
