# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0005_auto_20160408_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='id',
        ),
        migrations.AddField(
            model_name='annotation_vl',
            name='annotation_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotation_vl',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='annotation_vl',
            name='content_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='annotation_vl',
            name='distance',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='annotation_vl',
            name='fear',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='annotation_vl',
            name='humor_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='annotation_vl',
            name='source',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='annotation_vl',
            name='student_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='annotation_vl',
            name='tweet_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
