# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0007_auto_20160408_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation_eb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_id', models.BigIntegerField()),
                ('tweet_id', models.BigIntegerField()),
                ('student_id', models.BigIntegerField()),
                ('is_filled', models.BooleanField(default=False)),
                ('humor_type', models.CharField(blank=True, max_length=20, null=True)),
                ('distance', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(blank=True, max_length=20, null=True)),
                ('content_type', models.CharField(blank=True, max_length=20, null=True)),
                ('fear', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='annotation_vl',
            old_name='fear',
            new_name='attitude',
        ),
        migrations.AlterUniqueTogether(
            name='annotation_eb',
            unique_together=set([('tweet_id', 'student_id')]),
        ),
    ]
